### ISSUE TITLE
Temperature defaults to celsius and will not save change

### ISSUE THREAD

**Issue by m-milani** [regulad/hass-lacrosseview#7] opened 2022-05-23 15:19 UTC
I have an indoor and outdoor temperature sensor and the entities default to celsius.   I switch them to F and the setting does not save.

**Comment by m-milani** [comment] 2022-05-24 13:56
I have attempted to turn on debug for this module, and it seems that there are no debug symbols in the code.   

tried custom_components.lacrosseview: debug 
tried custom_components.pylacrosseview: debug

**Comment by regulad** [comment] 2022-05-29 19:56
I was able to reproduce this, but I have no idea how to fix it. I'm not the most experienced with Home Assistant, you might want to ask around in the forums. You are free to make a pull request if you identify a solution.

**Comment by tekwreck** [comment] 2022-05-30 02:57
I'm seeing this same issue as well :-)

**Comment by tekwreck** [comment] 2022-05-30 03:22
Not sure if this helps but I ran your example on pylacrosseview, the output shows Celcius from temperature before even getting to Home Assistant.

**Comment by regulad** [comment] 2022-06-04 13:07
> Not sure if this helps but I ran your example on pylacrosseview, the output shows Celcius from temperature before even getting to Home Assistant.

That's just the design of the backend and my library, I would have thought that HASS does the conversion work for me but I suppose I may be wrong.

**Comment by tekwreck** [comment] 2022-06-06 15:19
Yup, when I look at other weather station integrations, they do their own conversations in the code. Seems simple enough

**Comment by nocturne1** [comment] 2022-06-06 19:05
While not ideal, I've noticed that the HeatIndex value is coming through for me in F. So switching to that for now.

**Comment by nijel** [comment] 2022-06-17 13:40
HeatIndex seems to be always in F, temperatures in C.

**Comment by PachangaDad** [comment] 2022-08-06 16:20
First off a big thanks to the development of this. I was about to scrap my La Crosse platform for an alternative market solution. Now I'm thinking there is hope. I too see that the values of temperature that are being reflected in C vs F. Yet my weather station display shows  it in F. If I do the math of the reflected value of C to F, I have a match between this routine value and the weather station display. The heat index value, I assume is taking into consideration the humidity. Any chance this converting can be resolved in this custom integration before it comes to HA? This way the values lend themselves to proper variation of display within HA.
Just my thoughts and would offer testing any changes.
Thanks again

**Comment by regulad** [comment] 2022-10-05 16:00
Fixed this in latest release.

**Closed as completed by regulad** 2022-10-05 16:00 UTC
Labels: bug, help wanted

**Comment by nocturne1** [comment] 2022-10-05 16:42
Confirmed fixed - thanks!
